# Railway dynamic port (IMPORTANT)
server.port=${PORT:8080}

# Database (Railway variables)
spring.datasource.url=jdbc:mysql://${MYSQLHOST:${DB_HOST:localhost}}:${MYSQLPORT:${DB_PORT:3306}}/${MYSQLDATABASE:${DB_NAME:projectdb}}?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=${MYSQLUSER:${DB_USER:root}}
spring.datasource.password=${MYSQLPASSWORD:${DB_PASS:1234}}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT
jwt.secret=examsecretkeyexamsecretkeyexamsecretkey123
jwt.expiration=86400000